CREATE TABLE PERSON 
(
  IDPERSON    NUMBER(14) NOT NULL, 
  CNAME       VARCHAR2(50), 
  USERNAME    VARCHAR2(50), 
  EMAIL       VARCHAR2(50), 
  PHONE       VARCHAR2(50),
  WEBSITE     VARCHAR2(100), 
  PRIMARY KEY(IDPERSON)
);

CREATE TABLE ADDRESS_PERSON 
( 
  IDADDRESS   NUMBER(14) NOT NULL,
  IDPERSON    NUMBER(14) NOT NULL, 
  STREET      VARCHAR2(50), 
  SUITE       VARCHAR2(50), 
  CITY        VARCHAR2(50), 
  ZIPCODE     VARCHAR2(20),
  LAT         VARCHAR2(30),
  LNG         VARCHAR2(30),   
  PRIMARY KEY(IDADDRESS),
  CONSTRAINT FK_PERSON FOREIGN KEY (IDPERSON) REFERENCES person(IDPERSON)
);

CREATE TABLE COMPANY_PERSON 
( 
  IDCOMPANY   NUMBER(14) NOT NULL,
  IDPERSON    NUMBER(14) NOT NULL, 
  CNAME       VARCHAR2(60), 
  CATCHPRASE  VARCHAR2(200), 
  BS          VARCHAR2(200),    
  PRIMARY KEY(IDCOMPANY),
  CONSTRAINT FK_IDPERSON FOREIGN KEY (IDPERSON) REFERENCES person(IDPERSON)
);