CREATE TABLE RESULT_CALC 
(
  IDOPERACION NUMBER(14) NOT NULL, 
  NUMEROA     NUMBER(14), 
  NUMEROB     NUMBER(14),
  OPERACION   VARCHAR2(20), 
  RESULTADO   NUMBER(14),
  PRIMARY KEY(IDOPERACION)
);